name: Release Application

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dotnet-version tool
        run: dotnet tool install --global dotnet-version
        
      - name: Determine version
        id: determine-version
        run: dotnet version
      
      - name: Set VERSION environment variable
        run: |
          echo "VERSION=${{ steps.determine-version.outputs.version }}" >> $GITHUB_ENV

      - name: Replace settings.js file
        run: |
         echo "window.appSettings = { apiBaseUrl: '' };" > src/UserInterface/public/settings.js

      - name: Build and release React application
        working-directory: src/UserInterface
        run: |
          npm ci
          npm run build

      - name: Copy release to .NET project folder
        run: cp -r src/UserInterface/build src/Service/ConfigMan.Service/www

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Update assembly versions
        run: |
          dotnet msbuild /p:Version=${{ env.VERSION }} /t:UpdateAssemblyInfo
          dotnet build
      
      - name: Build and publish .NET application
        working-directory: src/Service/ConfigMan.Service
        run: dotnet publish -c Release -o publish

      - name: Publish Application
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            Release version ${{ env.VERSION }} of the application.
          draft: true
          prerelease: true
