name: Release Application

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace settings.js file
        run: |
         echo "window.appSettings = { apiBaseUrl: '' };" > src/UserInterface/public/settings.js

      - name: Build and release React application
        working-directory: src/UserInterface
        run: |
          npm ci
          npm run build

      - name: Copy release to .NET project folder
        run: cp -r src/UserInterface/build src/Service/ConfigMan.Service/www

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build and publish .NET application
        working-directory: src/Service
        run: dotnet publish -c Release -o publish

      - name: Publish Application
        run: |
          # You can replace the command below with the actual command to publish your application.
          echo "Publishing .NET application..."
